import type { ApiModel, EndpointModel } from '../analysis/apiModel';
import { declareType, typeNameFor } from './types';

export function methodNameFor(method: string, template: string): string {
  const name = typeNameFor(method, template, '');
  return name[0]!.toLowerCase() + name.slice(1);
}

function paramsOf(template: string): string[] {
  return Array.from(template.matchAll(/\{([^}]+)\}/g)).map((m) => m[1]!);
}

function successResponse(endpoint: EndpointModel) {
  return (
    endpoint.responses.find((r) => r.status >= 200 && r.status < 300) ??
    endpoint.responses[0]
  );
}

function responseSuffix(status: number): string {
  return status >= 200 && status < 300 ? 'Response' : `Response${status}`;
}

export function generateTypes(model: ApiModel): string {
  const lines = ['// Generated by xray. Types inferred from observed traffic.', ''];

  for (const endpoint of model.endpoints) {
    if (endpoint.requestSchema) {
      lines.push(
        declareType(
          typeNameFor(endpoint.method, endpoint.template, 'Request'),
          endpoint.requestSchema
        ),
        ''
      );
    }
    for (const response of endpoint.responses) {
      lines.push(
        declareType(
          typeNameFor(endpoint.method, endpoint.template, responseSuffix(response.status)),
          response.schema
        ),
        ''
      );
    }
  }

  return lines.join('\n');
}

export function generateClient(model: ApiModel): string {
  const imported = new Set<string>();
  const methods: string[] = [];

  for (const endpoint of model.endpoints) {
    const params = paramsOf(endpoint.template);
    const response = successResponse(endpoint);
    const responseType = response
      ? typeNameFor(endpoint.method, endpoint.template, responseSuffix(response.status))
      : 'unknown';
    if (response) imported.add(responseType);

    const args = params.map((p) => `${p}: string | number`);
    if (endpoint.requestSchema) {
      const requestType = typeNameFor(endpoint.method, endpoint.template, 'Request');
      imported.add(requestType);
      args.push(`body: ${requestType}`);
    }

    const path = endpoint.template.replace(/\{([^}]+)\}/g, '${$1}');
    const headers = [`'content-type': 'application/json'`];
    if (endpoint.auth === 'bearer') {
      headers.push(
        '...(this.token ? { Authorization: `Bearer ${this.token}` } : {})'
      );
    }

    methods.push(
      `  async ${methodNameFor(endpoint.method, endpoint.template)}(${args.join(', ')}): Promise<${responseType}> {
    const response = await this.fetchFn(\`\${this.baseUrl}${path}\`, {
      method: '${endpoint.method}',
      headers: { ${headers.join(', ')} },${
        endpoint.requestSchema ? '\n      body: JSON.stringify(body),' : ''
      }
    });
    if (!response.ok) {
      throw new Error(\`${endpoint.method} ${endpoint.template} failed: \${response.status}\`);
    }
    return (await response.json()) as ${responseType};
  }`
    );
  }

  const imports =
    imported.size > 0
      ? `import type {\n${Array.from(imported)
          .sort()
          .map((name) => `  ${name},`)
          .join('\n')}\n} from './types';\n\n`
      : '';

  return `// Generated by xray. One method per observed endpoint.
${imports}export type FetchFn = (
  input: string,
  init?: { method?: string; headers?: Record<string, string>; body?: string }
) => Promise<{ ok: boolean; status: number; json(): Promise<unknown> }>;

export class ApiClient {
  constructor(
    private readonly fetchFn: FetchFn,
    private readonly baseUrl: string = '${model.baseUrl ?? ''}',
    private token: string | null = null
  ) {}

  setToken(token: string | null): void {
    this.token = token;
  }

${methods.join('\n\n')}
}
`;
}
