import type { ApiModel } from '../analysis/apiModel';

export function templateToHonoPath(template: string): string {
  return template.replace(/\{([^}]+)\}/g, ':$1');
}

export function generateReplayServer(model: ApiModel): string {
  const routes = model.endpoints
    .map(
      (endpoint) =>
        `app.${endpoint.method.toLowerCase()}('${templateToHonoPath(endpoint.template)}', (c) => respond(c, '${endpoint.key}'));`
    )
    .join('\n');

  return `// Generated by xray. Replays responses captured from the original app.
import { Hono } from 'hono';
import { serveStatic } from 'hono/bun';
import type { Context } from 'hono';
import recordings from './recordings.json';

type Recording = { status: number; headers: Record<string, string>; body: unknown };

const app = new Hono();

function respond(c: Context, key: string) {
  const recorded = (recordings as Record<string, Recording[]>)[key];
  if (!recorded || recorded.length === 0) {
    // XRAY-GAP: no response was captured for this endpoint. Failing loudly is
    // deliberate — inventing one would make the reconstruction quietly wrong.
    return c.json(
      { error: 'XRAY-GAP', detail: \`no captured response for \${key}\` },
      501
    );
  }
  const pick = recorded[0]!;
  return c.json(pick.body as never, pick.status as never);
}

${routes}

// Static assets, then SPA fallback so client-side routes resolve on reload.
app.use('/*', serveStatic({ root: './dist' }));
app.get('*', serveStatic({ path: './dist/index.html' }));

const port = Number(process.env.PORT ?? 8787);
export default { port, fetch: app.fetch };
`;
}
