import type { ApiModel } from '../analysis/apiModel';

export function templateToHonoPath(template: string): string {
  return template.replace(/\{([^}]+)\}/g, ':$1');
}

/**
 * The first path segment shared by observed endpoints, e.g. `/api`. Requests
 * under it that were never captured must fail loudly rather than fall through
 * to the SPA fallback, which would answer 200 with the app shell.
 */
function apiPrefixes(model: ApiModel): string[] {
  const prefixes = new Set<string>();
  for (const endpoint of model.endpoints) {
    const first = endpoint.template.split('/').filter(Boolean)[0];
    if (first && !first.startsWith('{')) prefixes.add(`/${first}`);
  }
  return Array.from(prefixes).sort();
}

export function generateReplayServer(model: ApiModel): string {
  const routes = model.endpoints
    .map(
      (endpoint) =>
        `app.${endpoint.method.toLowerCase()}('${templateToHonoPath(endpoint.template)}', (c) => respond(c, '${endpoint.key}'));`
    )
    .join('\n');

  const gapGuards = apiPrefixes(model)
    .map(
      (prefix) =>
        `app.all('${prefix}/*', (c) =>\n  c.json(\n    { error: 'RAIDER-GAP', detail: \`no endpoint captured for \${c.req.method} \${c.req.path}\` },\n    501\n  )\n);`
    )
    .join('\n');

  return `// Generated by raider. Replays responses captured from the original app.
import { Hono } from 'hono';
import { serveStatic } from 'hono/bun';
import type { Context } from 'hono';
import recordings from './recordings.json';

type Recording = { status: number; headers: Record<string, string>; body: unknown };

const app = new Hono();

function respond(c: Context, key: string) {
  const recorded = (recordings as Record<string, Recording[]>)[key];
  if (!recorded || recorded.length === 0) {
    // RAIDER-GAP: no response was captured for this endpoint. Failing loudly is
    // deliberate — inventing one would make the reconstruction quietly wrong.
    return c.json(
      { error: 'RAIDER-GAP', detail: \`no captured response for \${key}\` },
      501
    );
  }
  const pick = recorded[0]!;
  return c.json(pick.body as never, pick.status as never);
}

${routes}

// Static assets first: an endpoint prefix like /hologram can also be a real
// content directory, and a file that exists must always win over a guard.
app.use('/*', serveStatic({ root: './dist' }));

// Only then: paths under an observed API prefix that were never captured.
// Answering these with the SPA shell would look like success; 501 says what is
// actually true.
${gapGuards}

// Finally the SPA fallback, so client-side routes resolve on reload.
app.get('*', serveStatic({ path: './dist/index.html' }));

const port = Number(process.env.PORT ?? 8787);
export default { port, fetch: app.fetch };
`;
}
